# Generated by Django 5.2.4 on 2025-07-13 16:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Member', 'Member')], help_text='What is the role of the member?', max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='pr_management.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(blank=True, default=True, editable=False, help_text='If this object is active')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='What is the task about?')),
                ('status', models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Done', 'Done')], help_text='What is the status of the task?', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], help_text='What is the priority of the task?', max_length=10)),
                ('due_date', models.DateTimeField(help_text='What is the expiry date of the task?', verbose_name='Expiry Date')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Who is assigned to this task?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Which project does this task belong to?', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pr_management.project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(blank=True, default=True, editable=False, help_text='If this object is active')),
                ('content', models.TextField(help_text='What is the content of the comment?')),
                ('user', models.ForeignKey(help_text='Who made the comment?', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(help_text='Which task does this comment belong to?', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pr_management.task')),
            ],
        ),
    ]
