# Generated by Django 5.2.4 on 2025-07-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pr_management', '0002_projectmember_task_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
